In [1]:
%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [2]:
from fastai.conv_learner import *
from fastai.dataset import *

import json, pdb
import pandas as pd
pd.set_option('display.max_columns', 500)
from PIL import ImageDraw, ImageFont
from matplotlib import patches, patheffects
torch.cuda.set_device(0)

In [3]:
torch.backends.cudnn.benchmark=True

In [4]:
train = pd.read_csv('train_with_labels_v3.csv')
train.head()

,OutputID,row_1_X_1,row_1_Y_1,row_1_X_2,row_1_Y_2,row_1_X_3,row_1_Y_3,row_1_X_4,row_1_Y_4,row_2_X_1,row_2_Y_1,row_2_X_2,row_2_Y_2,row_2_X_3,row_2_Y_3,row_2_X_4,row_2_Y_4,row_3_X_1,row_3_Y_1,row_3_X_2,row_3_Y_2,row_3_X_3,row_3_Y_3,row_3_X_4,row_3_Y_4,row_4_X_1,row_4_Y_1,row_4_X_2,row_4_Y_2,row_4_X_3,row_4_Y_3,row_4_X_4,row_4_Y_4,row_5_X_1,row_5_Y_1,row_5_X_2,row_5_Y_2,row_5_X_3,row_5_Y_3,row_5_X_4,row_5_Y_4,row_6_X_1,row_6_Y_1,row_6_X_2,row_6_Y_2,row_6_X_3,row_6_Y_3,row_6_X_4,row_6_Y_4,row_7_X_1,row_7_Y_1,row_7_X_2,row_7_Y_2,row_7_X_3,row_7_Y_3,row_7_X_4,row_7_Y_4,row_8_X_1,row_8_Y_1,row_8_X_2,row_8_Y_2,row_8_X_3,row_8_Y_3,row_8_X_4,row_8_Y_4,row_9_X_1,row_9_Y_1,row_9_X_2,row_9_Y_2,row_9_X_3,row_9_Y_3,row_9_X_4,row_9_Y_4,row_10_X_1,row_10_Y_1,row_10_X_2,row_10_Y_2,row_10_X_3,row_10_Y_3,row_10_X_4,row_10_Y_4,row_11_X_1,row_11_Y_1,row_11_X_2,row_11_Y_2,row_11_X_3,row_11_Y_3,row_11_X_4,row_11_Y_4,Type_0,Type_1,Type_2,Type_3,Type_4,Type_5,ImageLocation,MaskLocation
0,Image376_1TPP_4R_PL2.jpg,100,2587,3527,2619,3530,2353,100,2327,100,2316,3530,2347,3530,2077,102,2050,103,2041,3530,2072,3528,1803,105,1774,105,1764,3530,1796,3533,1533,108,1498,108,1488,3532,1529,3531,1259,114,1227,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3...."
1,Image208_1TPP_3R_MT.jpg,98,879,1529,894,1532,738,100,721,100,717,1536,736,1537,613,105,581,105,576,1538,605,1540,455,107,428,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3...."
2,Image212_1TPP_3R_MT.jpg,100,868,1531,886,1535,735,105,715,105,711,1537,732,1539,606,108,575,108,573,1541,600,1544,456,108,423,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3...."
3,Image202_1TPP_3R_MT.jpg,101,874,1531,891,1532,749,106,725,103,720,1534,740,1537,614,110,585,108,578,1539,611,1543,454,111,423,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3...."
4,Image242_2TPP_4R_MT.JPG,103,1754,2492,1758,2502,1586,108,1582,109,1575,2505,1580,2507,1400,103,1384,105,1380,2512,1397,2514,1219,95,1199,96,1196,2516,1214,2518,1031,98,1021,100,947,2519,960,2522,786,103,762,104,760,2520,782,2525,597,107,582,110,579,2526,591,2519,409,110,401,109,389,2516,405,2520,219,121,219,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3...."

In [5]:
IMG_PATH = 'data/train/'
height = []
width = []
for file in train.OutputID:
    img = cv2.imread(IMG_PATH+file, cv2.IMREAD_COLOR)
    img_shp = img.shape
    height.append(img_shp[0])
    width.append(img_shp[1])

In [6]:
train["height"] = height   #append height column to training dataset
train["width"] = width   #append width column to training dataset

In [7]:
categories = pd.DataFrame()
categories["id"] = [1, 2]
categories["name"] = ['supercorner', 'middle corner']
categories.head()

   id           name
0   1    supercorner
1   2  middle corner

In [8]:
def get_bbox(x, y, first_last = None):
    pass

In [9]:
def annotate(idx, num, x1, y1, x2, y2, x3, y3, x4, y4, ):
    pass

## Convert empty trays to np.NaN

In [10]:
for row in range(len(train.OutputID)):
    for r in range(1,12):
        x = 0
        y = 0
        for i in range(1,5):
            x += train.at[row,f'row_{r}_X_{i}']
            y += train.at[row,f'row_{r}_Y_{i}']
        if x + y == 0:
            for i in range(1,5):
                train.loc[[row],[f'row_{r}_X_{i}']] = np.NaN
                train.loc[[row],[f'row_{r}_Y_{i}']] = np.NaN

In [11]:
train.head()

,OutputID,row_1_X_1,row_1_Y_1,row_1_X_2,row_1_Y_2,row_1_X_3,row_1_Y_3,row_1_X_4,row_1_Y_4,row_2_X_1,row_2_Y_1,row_2_X_2,row_2_Y_2,row_2_X_3,row_2_Y_3,row_2_X_4,row_2_Y_4,row_3_X_1,row_3_Y_1,row_3_X_2,row_3_Y_2,row_3_X_3,row_3_Y_3,row_3_X_4,row_3_Y_4,row_4_X_1,row_4_Y_1,row_4_X_2,row_4_Y_2,row_4_X_3,row_4_Y_3,row_4_X_4,row_4_Y_4,row_5_X_1,row_5_Y_1,row_5_X_2,row_5_Y_2,row_5_X_3,row_5_Y_3,row_5_X_4,row_5_Y_4,row_6_X_1,row_6_Y_1,row_6_X_2,row_6_Y_2,row_6_X_3,row_6_Y_3,row_6_X_4,row_6_Y_4,row_7_X_1,row_7_Y_1,row_7_X_2,row_7_Y_2,row_7_X_3,row_7_Y_3,row_7_X_4,row_7_Y_4,row_8_X_1,row_8_Y_1,row_8_X_2,row_8_Y_2,row_8_X_3,row_8_Y_3,row_8_X_4,row_8_Y_4,row_9_X_1,row_9_Y_1,row_9_X_2,row_9_Y_2,row_9_X_3,row_9_Y_3,row_9_X_4,row_9_Y_4,row_10_X_1,row_10_Y_1,row_10_X_2,row_10_Y_2,row_10_X_3,row_10_Y_3,row_10_X_4,row_10_Y_4,row_11_X_1,row_11_Y_1,row_11_X_2,row_11_Y_2,row_11_X_3,row_11_Y_3,row_11_X_4,row_11_Y_4,Type_0,Type_1,Type_2,Type_3,Type_4,Type_5,ImageLocation,MaskLocation,height,width
0,Image376_1TPP_4R_PL2.jpg,100,2587,3527,2619,3530,2353,100,2327,100,2316,3530,2347,3530,2077,102,2050,103,2041,3530,2072,3528,1803,105,1774,105.0,1764.0,3530.0,1796.0,3533.0,1533.0,108.0,1498.0,108.0,1488.0,3532.0,1529.0,3531.0,1259.0,114.0,1227.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",2736,3648
1,Image208_1TPP_3R_MT.jpg,98,879,1529,894,1532,738,100,721,100,717,1536,736,1537,613,105,581,105,576,1538,605,1540,455,107,428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",1200,1600
2,Image212_1TPP_3R_MT.jpg,100,868,1531,886,1535,735,105,715,105,711,1537,732,1539,606,108,575,108,573,1541,600,1544,456,108,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",1200,1600
3,Image202_1TPP_3R_MT.jpg,101,874,1531,891,1532,749,106,725,103,720,1534,740,1537,614,110,585,108,578,1539,611,1543,454,111,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",1200,1600
4,Image242_2TPP_4R_MT.JPG,103,1754,2492,1758,2502,1586,108,1582,109,1575,2505,1580,2507,1400,103,1384,105,1380,2512,1397,2514,1219,95,1199,96.0,1196.0,2516.0,1214.0,2518.0,1031.0,98.0,1021.0,100.0,947.0,2519.0,960.0,2522.0,786.0,103.0,762.0,104.0,760.0,2520.0,782.0,2525.0,597.0,107.0,582.0,110.0,579.0,2526.0,591.0,2519.0,409.0,110.0,401.0,109.0,389.0,2516.0,405.0,2520.0,219.0,121.0,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",1944,2592

In [12]:
#train2 = pd.read_csv('train_with_labels_v3.csv')
for r in range(1,12):
    merged_rows = []
    for row in range(len(train.OutputID)):
        merged_row = []
        for i in range(1,5):
            merged_row.append(train.at[row,f'row_{r}_X_{i}'])
            merged_row.append(train.at[row,f'row_{r}_Y_{i}'])
        merged_rows.append(merged_row)
    train[f'row_{r}'] = merged_rows
    train.drop(list(train.filter(regex = f'row_{r}_')), axis = 1, inplace = True)

In [13]:
train.head(n=2)

,OutputID,Type_0,Type_1,Type_2,Type_3,Type_4,Type_5,ImageLocation,MaskLocation,height,width,row_1,row_2,row_3,row_4,row_5,row_6,row_7,row_8,row_9,row_10,row_11
0,Image376_1TPP_4R_PL2.jpg,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",2736,3648,"[100, 2587, 3527, 2619, 3530, 2353, 100, 2327]","[100, 2316, 3530, 2347, 3530, 2077, 102, 2050]","[103, 2041, 3530, 2072, 3528, 1803, 105, 1774]","[105.0, 1764.0, 3530.0, 1796.0, 3533.0, 1533.0...","[108.0, 1488.0, 3532.0, 1529.0, 3531.0, 1259.0...","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"
1,Image208_1TPP_3R_MT.jpg,1,0,0,0,0,0,https://firebasestorage.googleapis.com/v0/b/la...,"{""Type0_straight_tray"":""https://imagemasks.s3....",1200,1600,"[98, 879, 1529, 894, 1532, 738, 100, 721]","[100, 717, 1536, 736, 1537, 613, 105, 581]","[105, 576, 1538, 605, 1540, 455, 107, 428]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]","[nan, nan, nan, nan, nan, nan, nan, nan]"

In [29]:
## need to melt columns to rows:
## https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.wide_to_long.html
train = pd.wide_to_long(train, stubnames='row_', i=['OutputID'], j='row')

In [31]:
train.head(n=2)

,,ImageLocation,width,Type_5,Type_3,Type_4,height,Type_2,Type_1,MaskLocation,Type_0,row_
OutputID,row,,,,,,,,,,,
Image376_1TPP_4R_PL2.jpg,1,https://firebasestorage.googleapis.com/v0/b/la...,3648,0,0,0,2736,0,0,"{""Type0_straight_tray"":""https://imagemasks.s3....",1,"[100, 2587, 3527, 2619, 3530, 2353, 100, 2327]"
Image208_1TPP_3R_MT.jpg,1,https://firebasestorage.googleapis.com/v0/b/la...,1600,0,0,0,1200,0,0,"{""Type0_straight_tray"":""https://imagemasks.s3....",1,"[98, 879, 1529, 894, 1532, 738, 100, 721]"

In [32]:
def mk_bbox(output_id, height, width, coords):
    
    pass